### ISSUE TITLE
youtube-dl -g option ?

### ISSUE THREAD

**Issue by Gboy9155** [BrianAllred/NYoutubeDL#10]
Hello,

I just installed your wrapper but i haven't find the option to get the direct link (the -g option in youtube-dl).
Did NYoutubeDl has this option ? If not, would you plain to wrap it?

Thanks for reading, Best regards.

**Comment by BrianAllred** [comment]
Duplicate #8

**Comment by BrianAllred** [comment]
Yeah, definitely plan on it, I just haven't had a lot of time until recently. Luckily, my time has opened up lately, so I should be able to get an update out soon.

**Comment by BrianAllred** [comment]
Oh, I thought you were talking about the new geo-restriction stuff. "-g" is in the VerbositySimulation options. You can set it like this

    var ydlClient = new YoutubeDL();
    ydlClient.Options.VerbositySimulationOptions.GetUrl = true
