### ISSUE TITLE
Can using this as a DLL for Unity Engine

### ISSUE THREAD

**Issue by popeyaho** [BrianAllred/NYoutubeDL#11]
This library looks nice, I'm finding the lib can using for Unity and I'm here, so can using this lib as a DLL.
Sorry for noob question, thank you so much for that!

**Comment by BrianAllred** [comment]
Unfortunately, no, Unity does not currently support .NET Standard 2.0 libraries. According to the team, support will come either in version 2017.3 or 2018.1.
