### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by ahmedmohamedfci** [BrianAllred/NYoutubeDL#12]
i am trying to install it to my project but it keeps saying:
```
Install-Package : Could not install package 'NYoutubeDL 0.6.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does
 not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

i am new to nuget, can you please provide clear installation instructions?
thank you

**Comment by BrianAllred** [comment]
NYoutubeDL is a .NET Standard 2.0 library, so you must use it in conjunction with a compatible .NET version. I believe the lowest compatible versions are .NET Framework 4.6 and .NET Core 2.0.

If possible, re-target your application for .NET 4.6 (or higher) and try again.

**Comment by entrailz** [comment]
I'm having the same issue - I've installed the newest .net core, .net standard and .net framework dev tools, targeted it to .net framework 4.7.2 but still get the exact same error.

**Comment by BrianAllred** [comment]
I can't reproduce it with a .NET 4.6+ project. You're sure that your version is correct?

![image](https://user-images.githubusercontent.com/5847511/40523733-af6414d8-5f9c-11e8-9914-268a3f1a64aa.png)

![image](https://user-images.githubusercontent.com/5847511/40523808-fef44eb4-5f9c-11e8-93c5-eb831a9e7af5.png)

**Comment by entrailz** [comment]
Was able to resolve -- had to force an update for Visual Studio to 15.3.
