### ISSUE TITLE
implement output template

### ISSUE THREAD

**Issue by MasterDomino** [BrianAllred/NYoutubeDL#13]
we can read more about it [there](https://github.com/rg3/youtube-dl/blob/master/README.md#output-template), it allows us to get the filename dynamically

**Comment by BrianAllred** [comment]
This already works.

    ydlClient.Options.FilesystemOptions.Output = @"%(title)s-%(uploader)s-%(id)s";

will output a file called "VR CHAT (2nd Second Life) - videogamedunkey - eR7yRKBromQ" for the video at https://www.youtube.com/watch?v=eR7yRKBromQ.
