### ISSUE TITLE
Get availible subtitles list

### ISSUE THREAD

**Issue by GooG2e** [BrianAllred/NYoutubeDL#14]
Hello!
I want to receive availible subtitle list, but I can't receive it because StandardOutputEvent and StandardErrorEvent don't receive this lines of output.
Please help with this!

**Comment by BrianAllred** [comment]
I can't reproduce. Make sure you're setting `Options.SubtitleOptions.ListSubs = true` and that the video actually has subtitles. Also make sure that your youtube-dl binary is up to date. You can do this in code if you wish (and you have appropriate permissions to overwrite the binary).

    ydlClient.Options.GeneralOptions.Update = true
    ydlClient.Download(true).WaitForExit();

As of writing this comment, the current version is 2017.12.23.

If you can reproduce using the current version of youtube-dl, re-open this issue with example code and I'll take a closer look.
