### ISSUE TITLE
Getting description, thumbnail, duration etc.

### ISSUE THREAD

**Issue by fergalmoran** [BrianAllred/NYoutubeDL#4]
Really nice library!

Struggling a bit to see how to get attributes such as duration, thumbnail.
I can see the youtube_dl flags in VerbositySimulation.cs but unsure how to access this metadata?

Thanks!!

Fergal

**Comment by BrianAllred** [comment]
Since the library is just a wrapper for youtube-dl, you'll need to either subscribe to youtube-dl's console output for info like duration, or perform the download for the thumbnail and then find image on disk.

**Comment by fergalmoran** [comment]
Thanks Brian...
I don't need to download the image though - I just want the url of it.
I guess what I'm asking is how would I do the equivalent of 
```
youtube-dl --get-description  <url>
youtube-dl --get-thumbnail <url>
youtube-dl --get-duration <url>
```
or even better - get access to the entire json object from
```
youtube-dl -j <url>
```

Something like
```
var yt = new YoutubeDL();
var desc = yt.GetDescription(); //youtube-dl --get-description  <url>
var thumb = yt.GetThumbnail(); //youtube-dl --get-thumbnail <url>
//or even better
dynamic metaData = yt.GetMetaData(); //youtube-dl -j <url>
```

I've spelunked the code a bit but I can't see how to easily do this, if it's not available I'd be happy to create a pull request but I'm not convinced I'd be able to do it elegantly as I'm not hugely familiar with the code?

**Comment by BrianAllred** [comment]
The code base has support for all of youtube-dl's options, so to do something like 

```
youtube-dl -j <url>
```

you would write code that looks like

```
var ytClient = new YoutubeDL();
ytClient.Options.VerbositySimulationOptions.DumpJson = true;
ytClient.VideoUrl = <url>;
ytClient.StandardOutputEvent += delegate{ /* capture JSON string here */ };
ytClient.Download(true);
```

For a more broad overview, the meat of this library is simply exposing youtube-dl's switch options. The options are organized according to the official youtube-dl documentation. When you enable or use an option, you are adding it to the command line execution. For example,

```
ytClient.Options.PostProcessingOptions.ExtractAudio = true;
ytClient.Options.PostProcessingOptions.KeepVideo = true;
ytClient.Options.ThumbnailImagesOptions.WriteAllThumbnails = true;
ytClient.Options.FilesystemOptions.Output = "~/Downloads";
```

would result in the following execution

```
youtube-dl -x -k --write-all-thumbnails -o "~/Downloads" <url>
```

Then, you can either parse out the console output (if you subscribed to it), or do what you need to with the downloaded files (video, audio, images, etc).

Hope this helps! :)

**Comment by BrianAllred** [comment]
Also, if you need to find a specific youtube-dl dash option, search the repo for it. You'll find exactly where it lives.

**Comment by fergalmoran** [comment]
Ah! Subscribing to the StandardOutputEvent was the piece I was missing.
Thanks for your help, Brian!

**Comment by fergalmoran** [comment]
Ok - sorry but I'm still having issues here. I can download a link, or I can get the extra info for a link but I'm having issues doing both together. I have a gist here showing where I currently am, if you had time to take a look I'd appreciate it. I understand if git issues isn't the right place for this.

https://gist.github.com/fergalmoran/6a06190335bfe0ec36bca44e2f0e85b0

**Comment by BrianAllred** [comment]
Sadly, I believe this js a limitation of youtube-dl. If you append the `-j` option, then it won't download the actual video. Since this library is just a wrapper running the tool, I can't change that behavior. I'm working on a GUI that implements this library, and I have to separate the logic just as you have.

**Comment by fergalmoran** [comment]
Yeah - I figured that and doing it that way doesn't bother me all that much (as you say, it's the same using youtube-dl on the CLI) but the above gist doesn't work. I have two separate instances of YoutubeDl - one for downloading and one for getting info - the problem is that the second instance never completes (even if I reverse the order of them, or try re-using the same instance)?

**Comment by BrianAllred** [comment]
Haven't forgotten about this, just been trying to find time. Should be able to investigate soon.

**Comment by BrianAllred** [comment]
It looks like the dump JSON download is erroring out because I'm trying to parse out stuff that isn't there. There's a try-catch I need to add.

**Comment by fergalmoran** [comment]
No problem, Brian. I've actually gone back to doing this myself using System.Process. It's not pretty but It works for my purposes for now so I'm in no rush - I'll keep an eye out for a fix here though!!

**Comment by BrianAllred** [comment]
Starting with version 0.5.0, you can now do two things to get this info.

* I've added almost all the video metadata to the VideoDownloadInfo class. This means you can set the video URL, perform a PrepareDownload, then inspect the Info property of the ydlClient, like so:

        ydlClient.VideoUrl = "https://www.youtube.com/watch?v=dQw4w9WgXcQ";
        ydlClient.PrepareDownload();
        if (ydlClient.Info is VideoDownloadInfo info)
        {
            string desc = info.Description;
            // Etc.
        }

* Alternatively, I added exception handling to the area of the code that was blowing up previously. So you can set the DumpJson / DumpSingleJson options, perform the download, and parse the JSON yourself, if you like.

This version will be published to NuGet shortly, if it's not already.

**Comment by fergalmoran** [comment]
Great work, Brian. I'll try this out and let you know!

**Comment by fergalmoran** [comment]
Hi Brian, apologies for the long delay here but I've had some time to look at your new additions recently and it's excellent, completely fills in the pieces that were missing for me. I've entirely replaced my own wrapper with this and it looks & performs much better. Thanks a lot!
